#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

MODE="${MODE:-smoke}"
PROFILE="${PROFILE:-bmq_safe}"
DATA_ROOT="${DATA_ROOT:-/root/autodl-tmp/DATA_ROOT/}"
PYTHON_BIN="${PYTHON_BIN:-/root/miniconda3/envs/bdetr/bin/python}"
PROTECTED_V19="${PROTECTED_V19:-${DATA_ROOT%/}/protected_mcln_artifacts/scanrefer_network_best_v19_rec025_0.581195_mask025_0.598233.pth}"
PROTECTED_V19_SHA256="${PROTECTED_V19_SHA256:-2d6a3cf2914e5a7394ff2072378613314aae6d44c0dfa03762dcbb6e55ececbe}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${ROOT_DIR}/experiment_output/v51_bmq_rank}"
LOCK_FILE="${LOCK_FILE:-${OUTPUT_ROOT}/v51_bmq_rank_${PROFILE}_${MODE}.lock}"

PRESERVE_PARENT_SCORE=0
CANDIDATE_PROMOTION_MARGIN=0.0
USE_MASK_CALIBRATION=1
USE_SOURCE_MASK_EVIDENCE=1
USE_SPATIAL_MASK_REFINER=1
CANDIDATE_MASK_LOSS_WEIGHT=0.25
CANDIDATE_LOVASZ_LOSS_WEIGHT=0.05
USE_PARENT_TRANSITION_ADVANTAGE=0
PARENT_TRANSITION_BREAK_COST=4.0
LISTWISE_LOSS_WEIGHT=1.0
TRANSITION_LOSS_WEIGHT=0.0
TRANSITION_BREAK_COST=4.0
TRANSITION_NEUTRAL_WEIGHT=0.25
AUX_LOSS_WEIGHT=1.0
SOURCE_MIX_LOSS_WEIGHT=0.25
SOURCE_MIX_QUERY_FOCUS_WEIGHT=0.75
USE_ADAPTIVE_SOURCE_MIXING=1
USE_SACR=1
JOINT_SOURCE_NAMES=default,contrastive_text,mask_text,sacr_structured
PARENT_TRANSITION_CANDIDATE_TOP_K=0

case "${PROFILE}" in
  anchor)
    USE_METRIC_UTILITY=0
    PAIRWISE_LOSS_WEIGHT=0.0
    DEPLOY_CANDIDATE_TOP_K=0
    SOURCE_CANDIDATE_TOP_K=0
    ORACLE_CANDIDATE_TOP_K=0
    MAX_DELTA=0.25
    JOINT_LR=1e-4
    ANCHOR_LOSS_WEIGHT=2.0
    INITIALIZATION_PROFILE=v51_anchor
    ;;
  parent_transition)
    USE_METRIC_UTILITY=0
    PAIRWISE_LOSS_WEIGHT=0.0
    DEPLOY_CANDIDATE_TOP_K=0
    SOURCE_CANDIDATE_TOP_K=0
    ORACLE_CANDIDATE_TOP_K=0
    MAX_DELTA=0.25
    JOINT_LR=3e-4
    ANCHOR_LOSS_WEIGHT=0.0
    INITIALIZATION_PROFILE=v52_parent_transition
    PRESERVE_PARENT_SCORE=1
    CANDIDATE_PROMOTION_MARGIN=0.05
    USE_PARENT_TRANSITION_ADVANTAGE=1
    PARENT_TRANSITION_CANDIDATE_TOP_K=32
    LISTWISE_LOSS_WEIGHT=0.0
    TRANSITION_LOSS_WEIGHT=1.0
    TRANSITION_BREAK_COST=1.0
    TRANSITION_NEUTRAL_WEIGHT=1.0
    AUX_LOSS_WEIGHT=0.0
    SOURCE_MIX_LOSS_WEIGHT=0.0
    SOURCE_MIX_QUERY_FOCUS_WEIGHT=0.0
    USE_ADAPTIVE_SOURCE_MIXING=0
    USE_SACR=0
    JOINT_SOURCE_NAMES=default,contrastive_text,mask_text
    USE_MASK_CALIBRATION=0
    USE_SOURCE_MASK_EVIDENCE=0
    USE_SPATIAL_MASK_REFINER=0
    CANDIDATE_MASK_LOSS_WEIGHT=0.0
    CANDIDATE_LOVASZ_LOSS_WEIGHT=0.0
    ;;
  parent_safe)
    USE_METRIC_UTILITY=0
    PAIRWISE_LOSS_WEIGHT=0.0
    DEPLOY_CANDIDATE_TOP_K=0
    SOURCE_CANDIDATE_TOP_K=0
    ORACLE_CANDIDATE_TOP_K=0
    MAX_DELTA=0.25
    JOINT_LR=1e-4
    ANCHOR_LOSS_WEIGHT=2.0
    INITIALIZATION_PROFILE=v51_parent_promotion
    PRESERVE_PARENT_SCORE=1
    CANDIDATE_PROMOTION_MARGIN=0.05
    USE_MASK_CALIBRATION=0
    USE_SOURCE_MASK_EVIDENCE=0
    USE_SPATIAL_MASK_REFINER=0
    CANDIDATE_MASK_LOSS_WEIGHT=0.0
    CANDIDATE_LOVASZ_LOSS_WEIGHT=0.0
    ;;
  bmq_safe)
    USE_METRIC_UTILITY=1
    PAIRWISE_LOSS_WEIGHT=0.25
    DEPLOY_CANDIDATE_TOP_K=16
    SOURCE_CANDIDATE_TOP_K=8
    ORACLE_CANDIDATE_TOP_K=4
    MAX_DELTA=0.50
    JOINT_LR=1e-4
    ANCHOR_LOSS_WEIGHT=2.0
    INITIALIZATION_PROFILE=v51_bmq_rank
    ;;
  *)
    echo "PROFILE must be anchor, parent_transition, parent_safe, or bmq_safe" >&2
    exit 2
    ;;
esac

case "${MODE}" in
  smoke)
    GPU_IDS="${GPU_IDS:-0}"
    NPROC_PER_NODE="${NPROC_PER_NODE:-1}"
    MASTER_PORT="${MASTER_PORT:-4851}"
    BATCH_SIZE="${BATCH_SIZE:-12}"
    MAX_EPOCH="${MAX_EPOCH:-2}"
    EXPECTED_EVAL_SAMPLE_COUNT="${EXPECTED_EVAL_SAMPLE_COUNT:-128}"
    DEBUG=1
    PRINT_FREQ="${PRINT_FREQ:-1}"
    LOG_DIR="${LOG_DIR:-${DATA_ROOT%/}/output/double_stage_v51_bmq_smoke}"
    ;;
  formal)
    GPU_IDS="${GPU_IDS:-0,1,2,3}"
    NPROC_PER_NODE="${NPROC_PER_NODE:-4}"
    MASTER_PORT="${MASTER_PORT:-4852}"
    BATCH_SIZE="${BATCH_SIZE:-12}"
    MAX_EPOCH="${MAX_EPOCH:-40}"
    EXPECTED_EVAL_SAMPLE_COUNT="${EXPECTED_EVAL_SAMPLE_COUNT:-9508}"
    DEBUG=0
    PRINT_FREQ="${PRINT_FREQ:-100}"
    LOG_DIR="${LOG_DIR:-${DATA_ROOT%/}/output/double_stage_v51_bmq_formal}"
    ;;
  *)
    echo "MODE must be smoke or formal" >&2
    exit 2
    ;;
esac

mkdir -p "${OUTPUT_ROOT}" "${LOG_DIR}"
exec 9>"${LOCK_FILE}"
if ! flock -n 9; then
  echo "another V51 BMQ-Rank ${MODE} run owns ${LOCK_FILE}" >&2
  exit 3
fi

timestamp="$(date '+%Y%m%d_%H%M%S')"
EXP="v51_${PROFILE}_${MODE}_e1_e${MAX_EPOCH}_b${BATCH_SIZE}x${NPROC_PER_NODE}"
LAUNCH_LOG="${OUTPUT_ROOT}/${EXP}_${timestamp}.log"
exec > >(tee -a "${LAUNCH_LOG}") 2>&1

actual_sha256="$(sha256sum "${PROTECTED_V19}" | awk '{print $1}')"
if [[ "${actual_sha256}" != "${PROTECTED_V19_SHA256}" ]]; then
  echo "protected V19 SHA-256 changed" >&2
  exit 4
fi

initialization_audit="${OUTPUT_ROOT}/${INITIALIZATION_PROFILE}_protected_v19_initialization.json"
"${PYTHON_BIN}" scripts/audit_joint_query_initialization.py \
  --checkpoint "${PROTECTED_V19}" \
  --profile "${INITIALIZATION_PROFILE}" \
  --output "${initialization_audit}"

echo "[$(date '+%Y-%m-%d %H:%M:%S %Z')] starting ${EXP} on GPUs ${GPU_IDS}"
CUDA_VISIBLE_DEVICES="${GPU_IDS}" \
DATA_ROOT="${DATA_ROOT}" \
PYTHON_BIN="${PYTHON_BIN}" \
NPROC_PER_NODE="${NPROC_PER_NODE}" \
MASTER_PORT="${MASTER_PORT}" \
CHECKPOINT_PATH="${PROTECTED_V19}" \
LOG_DIR="${LOG_DIR}" \
EXP="${EXP}" \
MODEL_STAGE=two \
SOURCE_ARBITER=moe \
BATCH_SIZE="${BATCH_SIZE}" \
NUM_WORKERS=4 \
DATALOADER_PREFETCH_FACTOR=1 \
PERSISTENT_TRAIN_WORKERS=0 \
START_EPOCH=1 \
MAX_EPOCH="${MAX_EPOCH}" \
VAL_FREQ=1 \
PRINT_FREQ="${PRINT_FREQ}" \
EXPECTED_EVAL_SAMPLE_COUNT="${EXPECTED_EVAL_SAMPLE_COUNT}" \
DEBUG="${DEBUG}" \
JOINT_QUERY_QUALITY_LR="${JOINT_LR}" \
JOINT_QUERY_QUALITY_MAX_DELTA="${MAX_DELTA}" \
JOINT_QUERY_QUALITY_PRESERVE_PARENT_SCORE="${PRESERVE_PARENT_SCORE}" \
JOINT_QUERY_QUALITY_CANDIDATE_PROMOTION_MARGIN="${CANDIDATE_PROMOTION_MARGIN}" \
JOINT_QUERY_QUALITY_USE_PARENT_TRANSITION_ADVANTAGE="${USE_PARENT_TRANSITION_ADVANTAGE}" \
JOINT_QUERY_QUALITY_PARENT_TRANSITION_BREAK_COST="${PARENT_TRANSITION_BREAK_COST}" \
JOINT_QUERY_QUALITY_PARENT_TRANSITION_CANDIDATE_TOP_K="${PARENT_TRANSITION_CANDIDATE_TOP_K}" \
JOINT_QUERY_QUALITY_USE_MASK_CALIBRATION="${USE_MASK_CALIBRATION}" \
JOINT_QUERY_QUALITY_USE_SOURCE_MASK_EVIDENCE="${USE_SOURCE_MASK_EVIDENCE}" \
JOINT_QUERY_QUALITY_USE_SPATIAL_MASK_REFINER="${USE_SPATIAL_MASK_REFINER}" \
JOINT_QUERY_QUALITY_USE_ADAPTIVE_SOURCE_MIXING="${USE_ADAPTIVE_SOURCE_MIXING}" \
JOINT_QUERY_QUALITY_USE_SOURCE_DISTRIBUTION_RELIABILITY=0 \
JOINT_QUERY_QUALITY_SOURCE_NAMES="${JOINT_SOURCE_NAMES}" \
JOINT_QUERY_QUALITY_MASK_WEIGHT=0.25 \
JOINT_QUERY_QUALITY_TEMPERATURE=0.25 \
JOINT_QUERY_QUALITY_DIRECT_RESIDUAL_SCALE=0.25 \
JOINT_QUERY_QUALITY_USE_METRIC_ALIGNED_UTILITY="${USE_METRIC_UTILITY}" \
JOINT_QUERY_QUALITY_METRIC_UTILITY_TEMPERATURE=0.05 \
JOINT_QUERY_QUALITY_BIDIRECTIONAL_ANCHOR=1 \
JOINT_QUERY_QUALITY_ANCHOR_LOSS_WEIGHT="${ANCHOR_LOSS_WEIGHT}" \
JOINT_QUERY_QUALITY_ANCHOR_MARGIN=0.05 \
JOINT_QUERY_QUALITY_ANCHOR_MARGIN_050=0.10 \
JOINT_QUERY_QUALITY_PAIRWISE_LOSS_WEIGHT="${PAIRWISE_LOSS_WEIGHT}" \
JOINT_QUERY_QUALITY_LISTWISE_LOSS_WEIGHT="${LISTWISE_LOSS_WEIGHT}" \
JOINT_QUERY_QUALITY_TRANSITION_LOSS_WEIGHT="${TRANSITION_LOSS_WEIGHT}" \
JOINT_QUERY_QUALITY_TRANSITION_BREAK_COST="${TRANSITION_BREAK_COST}" \
JOINT_QUERY_QUALITY_TRANSITION_NEUTRAL_WEIGHT="${TRANSITION_NEUTRAL_WEIGHT}" \
JOINT_QUERY_QUALITY_DEPLOY_CANDIDATE_TOP_K="${DEPLOY_CANDIDATE_TOP_K}" \
JOINT_QUERY_QUALITY_SOURCE_CANDIDATE_TOP_K="${SOURCE_CANDIDATE_TOP_K}" \
JOINT_QUERY_QUALITY_ORACLE_CANDIDATE_TOP_K="${ORACLE_CANDIDATE_TOP_K}" \
JOINT_QUERY_QUALITY_CANDIDATE_MASK_LOSS_WEIGHT="${CANDIDATE_MASK_LOSS_WEIGHT}" \
JOINT_QUERY_QUALITY_CANDIDATE_LOVASZ_LOSS_WEIGHT="${CANDIDATE_LOVASZ_LOSS_WEIGHT}" \
JOINT_QUERY_QUALITY_CANDIDATE_MASK_TOP_K=16 \
JOINT_QUERY_QUALITY_MAX_SPATIAL_MASK_DELTA=2.0 \
JOINT_QUERY_QUALITY_MAX_SOURCE_MIX_DELTA=1.0 \
JOINT_QUERY_QUALITY_SOURCE_MIX_TEMPERATURE=0.5 \
JOINT_QUERY_QUALITY_AUX_LOSS_WEIGHT="${AUX_LOSS_WEIGHT}" \
JOINT_QUERY_QUALITY_SOURCE_MIX_LOSS_WEIGHT="${SOURCE_MIX_LOSS_WEIGHT}" \
JOINT_QUERY_QUALITY_SOURCE_MIX_ALIGNMENT_TEMPERATURE=0.25 \
JOINT_QUERY_QUALITY_SOURCE_MIX_QUERY_FOCUS_WEIGHT="${SOURCE_MIX_QUERY_FOCUS_WEIGHT}" \
USE_SACR_SOURCE="${USE_SACR}" \
SACR_RESIDUAL_SCALE_INIT=0.1 \
SACR_MIN_PARSE_CONFIDENCE=0.0 \
bash scripts/train_scanrefer_joint_query_quality.sh

echo "[$(date '+%Y-%m-%d %H:%M:%S %Z')] finished ${EXP}"
